# Generated by Django 5.2 on 2025-06-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyprofile',
            name='student_type',
            field=models.CharField(choices=[('Korean', '한국 학생'), ('International', '국제 학생')], default='Korean', max_length=20),
        ),
    ]
