# Generated by Django 5.2 on 2025-06-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_boardpost_event_end_boardpost_event_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='image_file/'),
        ),
    ]
