# Generated by Django 5.2 on 2025-06-07 08:46

import board.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_boardpost_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardpost',
            name='image_file',
        ),
        migrations.CreateModel(
            name='BoardPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_image', models.ImageField(upload_to=board.models.board_image_upload_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='board.boardpost')),
            ],
        ),
    ]
